<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE event [<!ELEMENT zip_code (#PCDATA)><!ELEMENT url_link_display (#PCDATA)><!ELEMENT url (#PCDATA)><!ELEMENT tracks (track+)><!ELEMENT track (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT timeslot (slot_id?, title, room, date, start_time, end_time, description?, acm_doi?, persons?, tracks?, tags?)><!ELEMENT tags (tag+)><!ELEMENT tag (#PCDATA)><!ELEMENT suffix (#PCDATA)><!ELEMENT subevent_logo_url (#PCDATA)><!ELEMENT subevent_id (#PCDATA)><!ELEMENT subevent (subevent_id?, title, acronym?, subevent_type, description?, room, date, url?, url_link_display?, subevent_logo_url?, acm_doi?, persons?, tracks?, tags?, sponsor?, timeslot*)><!ELEMENT state (#PCDATA)><!ELEMENT start_time (#PCDATA)><!ELEMENT start_date (#PCDATA)><!ELEMENT sponsor (#PCDATA)><!ELEMENT sort_key (#PCDATA)><!ELEMENT slot_id (#PCDATA)><!ELEMENT subevent_type EMPTY><!ATTLIST subevent_type	type (case_study | demonstration | poster | regular | tutorial | workshop) #IMPLIED><!ELEMENT room (#PCDATA)><!ELEMENT role (#PCDATA)><!ELEMENT picture_url (#PCDATA)><!ELEMENT persons (person+)><!ELEMENT person (role, sort_key, first_name, middle_name?, last_name, suffix?, affiliation, acm_profile_id?, email?, bio?, homepage_url?, picture_url?)><!ELEMENT middle_name (#PCDATA)><!ELEMENT location (facility_name, facility_map_url?, address, city, state?, country, zip_code?)><!ELEMENT last_name (#PCDATA)><!ELEMENT homepage_url (#PCDATA)><!ELEMENT first_name (#PCDATA)><!ELEMENT facility_name (#PCDATA)><!ELEMENT facility_map_url (#PCDATA)><!ELEMENT event_type EMPTY><!ATTLIST event_type	type (conference|workshop|symposium) #IMPLIED><!ELEMENT event (event_details, subevent*, timeslot*)><!ELEMENT event_logo_url (#PCDATA)><!ELEMENT event_details (title, acronym, event_type, start_date, end_date, location, description, url?, url_link_display?, event_logo_url?, persons?)><!ELEMENT end_time (#PCDATA)><!ELEMENT end_date (#PCDATA)><!ELEMENT email (#PCDATA)><!ELEMENT description (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT country (#PCDATA)><!ELEMENT city (#PCDATA)><!ELEMENT bio (#PCDATA)><!ELEMENT affiliation (#PCDATA)><!ELEMENT address (#PCDATA)><!ELEMENT acronym (#PCDATA)><!ELEMENT acm_profile_id (#PCDATA)><!ELEMENT acm_doi (#PCDATA)>]>
<event>
  <event_details>
    <title>PLDI 2017</title>
    <acronym>PLDI 2017</acronym>
    <event_type type="conference"/>
    <start_date>2017/06/18</start_date>
    <end_date>2017/06/23</end_date>
    <location>
      <facility_name>Universitat Polit√®cnica de Catalunya</facility_name>
      <address>Campus Nord, Carrer de Jordi Girona 1-3</address>
      <city>Barcelona</city>
      <country>Spain</country>
    </location>
    <description>Welcome to the website of the PLDI 2017 conference.
PLDI is the premier forum in the field of programming languages and programming systems research, covering the areas of design, implementation, theory, applications, and performance. The co-located conferences take place in Barcelona, June 18-23, 2017. 
Invited Speakers (joint with Curry On) 
 
 
  
  Mart&amp;iacute;n Abadi
  TensorFlow considered as a programming language
  
 
  
  Frank Wood
   Probabilistic Programming and Inference Compilation
  
 
  
  Martin Odersky
  What to leave implicit
  
 
 
 Student Travel Support Available 
SIGPLAN PAC may support travel, accommodation and registration for students who have a paper accepted at PLDI or co-located workshops. Hurry up to apply before May 1st! 
 
 Registration is now open! 
 PLDI registration gives you access to the Research Papers track and optionally to PLDI Workshops and Tutorials, LCTES, ISMM, ECOOP and DEBS. Visit the registration page for more details.  

PLDI welcomes outstanding research which clearly advances the field and has the potential to make a lasting contribution. 
Students can apply to volunteer at PLDI in exchange for free registration for the PLDI conference, workshops, panels and other co-located events. More info available at the student volunteers page.
PLDI will hold an ACM Student Research Competition and is now calling for submissions from undergraduate and graduate students. Submissions must include original, previously unpublished research. More info available at the PLDI SRC page.
SIGPLAN has opted to make access to published papers available for free via ACM OpenTOC. Accepted papers will be made available after the conference. 
 
 
  
  
 
  This year, PLDI is co-located with ECOOP, LCTES, DEBS, ISMM, Curry On and others. The conferences will take place at the Universitat Polyt&amp;egrave;cnica de Catalunya in Barcelona, Spain.</description>
    <url>http://pldi17.sigplan.org/home</url>
    <url_link_display>PLDI 2017</url_link_display>
    <persons>
      <person>
        <role>Chair in Steering Committee</role>
        <sort_key>1</sort_key>
        <first_name>Cormac</first_name>
        <last_name>Flanagan</last_name>
        <affiliation>University of California, Santa Cruz</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://users.soe.ucsc.edu/~cormac/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/cormacflanagan/fd454a8e-4230-4fa5-a4da-1d16a1027de3/small.jpg</picture_url>
      </person>
      <person>
        <role>General Chair in Organizing Committee</role>
        <sort_key>2</sort_key>
        <first_name>Albert</first_name>
        <last_name>Cohen</last_name>
        <affiliation>INRIA</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://who.rocq.inria.fr/Albert.Cohen</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/albertcohen/274c10d0-dc94-46c6-bde3-4077f30e13d8/small.jpg</picture_url>
      </person>
      <person>
        <role>Co-chair in Artifact Evaluation Committee, Artifact Evaluation Co-Chair in Organizing Committee</role>
        <sort_key>3</sort_key>
        <first_name>Murali</first_name>
        <last_name>Krishna Ramanathan</last_name>
        <affiliation>Indian Institute of Science, Bangalore</affiliation>
        <bio>Murali Krishna Ramanathan is an Assistant Professor in the Department of Computer Science and Automation at Indian Institute of Science, Bangalore. Before IISc, he was a member of the core analysis team at Coverity Inc. building program analysis tools for bug detection in industrial codebases, with an emphasis on finding concurrency defects. He received his PhD in Computer Science from Purdue University.</bio>
        <homepage_url>http://www.csa.iisc.ernet.in/~muralikrishna</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/muralikrishnaramanathan/52304999-046a-4d35-a2ed-9eb9ca2db709/small.jpg</picture_url>
      </person>
      <person>
        <role>Co-chair in Artifact Evaluation Committee, Committee Member in External Review Committee, Artifact Evaluation Co-Chair in Organizing Committee</role>
        <sort_key>4</sort_key>
        <first_name>Brandon</first_name>
        <last_name>Lucia</last_name>
        <affiliation>Carnegie Mellon University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://brandonlucia.com</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/brandonlucia/16fdd4eb-8f38-4c24-b29c-fa7ed8a15fb8/small.jpg</picture_url>
      </person>
      <person>
        <role>Chair in SRC Panel, Student Research Competition Chair in Organizing Committee</role>
        <sort_key>5</sort_key>
        <first_name>Xavier</first_name>
        <last_name>Martorell</last_name>
        <affiliation>Barcelona Supercomputing Center</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://www.bsc.es/martorell-bofill-xavier</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/xaviermartorell/38524045-2209-4f5a-b3be-24927f76f4d7/small.jpg</picture_url>
      </person>
      <person>
        <role>Program Chair in Program Committee, Program Chair in Organizing Committee</role>
        <sort_key>6</sort_key>
        <first_name>Martin</first_name>
        <last_name>Vechev</last_name>
        <affiliation>DeepCode and ETH Zurich, Switzerland</affiliation>
        <bio>I am an Assistant Professor of Computer Science at ETH Zurich where I lead the Software Reliability Lab. Prior to ETH, I was a Research Staff Member at the IBM T.J. Watson Research Center in New York. I obtained my PhD from Cambridge University, England and my B.Sc. from Simon Fraser University. I am interested in program analysis, program synthesis, application of machine learning to programming languages, and concurrency.</bio>
        <homepage_url>http://www.srl.inf.ethz.ch/vechev.php</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/martinvechev/1c8d199e-8f0e-435e-9b2c-506be67ed12c/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Artifact Evaluation Committee</role>
        <sort_key>7</sort_key>
        <first_name>Aravind</first_name>
        <last_name>Acharya</last_name>
        <affiliation>Indian Institute of Science, Bangalore</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://clweb.csa.iisc.ernet.in/aravind.acharya/</homepage_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>8</sort_key>
        <first_name>Sara</first_name>
        <last_name>Achour</last_name>
        <affiliation>MIT</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://people.csail.mit.edu/sachour/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/saraachour/f1aad314-c255-4cc9-97cd-2243cac4dcf7/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Program Committee</role>
        <sort_key>9</sort_key>
        <first_name>Eddie</first_name>
        <last_name>Aftandilian</last_name>
        <affiliation>Google</affiliation>
        <bio>I lead the Java Compiler Team at Google. A large part of our work focuses on lightweight static analysis to prevent bugs from entering Google‚Äôs Java codebase. We provide our bug detection tool, Error Prone (github.com/google/error-prone), as open source and as part of the Bazel (bazel.io) build system. Additionally, we provide tools that allow developers to refactor code at the scale of the whole Google codebase.</bio>
        <homepage_url>https://research.google.com/pubs/EdwardAftandilian.html</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/eddieaftandilian/4ada699b-4281-4cb2-a5fe-0d8015ff5c5b/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>10</sort_key>
        <first_name>Aws</first_name>
        <last_name>Albarghouthi</last_name>
        <affiliation>University of Wisconsin - Madison</affiliation>
        <bio>undefined</bio>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/awsalbarghouthi/3a3382aa-47f5-4e02-ac71-509eb94703ff/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>11</sort_key>
        <first_name>Nada</first_name>
        <last_name>Amin</last_name>
        <affiliation>EPFL</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://namin.net</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/nadaamin/b083e70b-31f9-4a88-89ba-ae54f8ec9315/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Program Committee</role>
        <sort_key>12</sort_key>
        <first_name>David F.</first_name>
        <last_name>Bacon</last_name>
        <affiliation>Google</affiliation>
        <bio>undefined</bio>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/davidfbacon/0fd9df29-594c-4341-bb5e-cb4bbf0edf5e/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Program Committee, Committee Member in Steering Committee</role>
        <sort_key>13</sort_key>
        <first_name>Emery</first_name>
        <last_name>Berger</last_name>
        <affiliation>University of Massachusetts, Amherst</affiliation>
        <bio>Emery Berger is a Professor in the School of Computer Science at the University of Massachusetts Amherst, the flagship campus of the UMass system. See his home page for more information.</bio>
        <homepage_url>http://www.cs.umass.edu/~emery/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/emeryberger/d4ec3e3a-5455-4f37-a497-42366bd39ce2/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee, Committee Member in External Review Committee</role>
        <sort_key>14</sort_key>
        <first_name>Steve</first_name>
        <last_name>Blackburn</last_name>
        <affiliation>Australian National University </affiliation>
        <bio>My research interests are centered on the challenge of making software run faster and more power-efficiently on modern hardware. My primary interests include: microarchitectural support for managed languages, fast and efficient garbage collection, and the design and implementation of virtual machines. As a backdrop to this I have a longstanding interest in role of sound methodology and infrastructure in successful research innovation.</bio>
        <homepage_url>http://users.cecs.anu.edu.au/~steveb/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/steveblackburn/1deee732-405d-4403-a974-a418751399c2/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in SRC Panel</role>
        <sort_key>15</sort_key>
        <first_name>Sandrine</first_name>
        <last_name>Blazy</last_name>
        <affiliation>University of Rennes 1, France</affiliation>
        <bio>I am professor in the computer science department of the University of Rennes 1, where I am in charge of the research master in computer science. I am a member of CELTIQUE, a joint project-team with Inria Rennes Bretagne Atlantique and the IRISA laboratory. 
My research activities concern the formal verification using the Coq proof assistant of program transformations and semantic properties of programming languages, such as those found in the CompCert compiler and the Verasco static analyzer. I teach mechanized semantics (in Coq), functional programming (in OCaml), formal methods (using the Why3 tool), and software vulnerabilities.</bio>
        <homepage_url>http://www.irisa.fr/celtique/blazy/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/sandrineblazy/bacd0031-1d22-476c-b6e5-fc58b1ab1177/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Artifact Evaluation Committee</role>
        <sort_key>16</sort_key>
        <first_name>Ben</first_name>
        <last_name>Blum</last_name>
        <affiliation>Carnegie Mellon University</affiliation>
        <bio>undefined</bio>
      </person>
      <person>
        <role>Committee Member in External Program Committee</role>
        <sort_key>17</sort_key>
        <first_name>Hans-J.</first_name>
        <last_name>Boehm</last_name>
        <affiliation>Google</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://hboehm.info</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/hansjboehm/286e268e-cfa4-4ce4-8898-ad67c5292241/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Program Committee</role>
        <sort_key>18</sort_key>
        <first_name>Michael</first_name>
        <last_name>Bond</last_name>
        <affiliation>Ohio State University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cse.ohio-state.edu/~mikebond</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/michaelbond/92c528d2-84b3-4369-8b57-6555f1016a8e/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Program Committee</role>
        <sort_key>19</sort_key>
        <first_name>Uday</first_name>
        <last_name>Bondhugula</last_name>
        <affiliation>Indian Institute of Science</affiliation>
        <bio>Uday Bondhugula is an Associate Professor in the department of Computer Science &amp;amp; Automation at the Indian Institute of Science (IISc), Bangalore, India. His research interests are in the design of new programming and compiler technologies for multicore architectures with an emphasis on high performance and automatic parallelization. Before joining IISc, he was with the Advanced Compiler Technologies group at the IBM T.J. Watson Research Center, Yorktown Heights, New York. He obtained his Ph.D. in Computer Science and Engineering from the Ohio State University, and his bachelor‚Äôs from the Indian Institute of Technology, Madras.</bio>
        <homepage_url>http://www.csa.iisc.ac.in/~uday</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/udaybondhugula/7e41aaae-8d52-473a-ba39-d2d1161c8810/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>20</sort_key>
        <first_name>James</first_name>
        <last_name>Bornholt</last_name>
        <affiliation>University of Washington</affiliation>
        <bio>I‚Äôm a computer science PhD student in the PLSE and Sampa groups at the University of Washington, advised by Emina Torlak, Dan Grossman, and Luis Ceze. I work on programming languages and formal methods, from program synthesis frameworks to consistency models.</bio>
        <homepage_url>https://homes.cs.washington.edu/~bornholt/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/jamesbornholt/3b627eda-8767-4bbc-b7f3-575ee248dc3e/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Program Committee</role>
        <sort_key>21</sort_key>
        <first_name>Ahmed</first_name>
        <last_name>Bouajjani</last_name>
        <affiliation>IRIF, Universit√© Paris Diderot</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://www.irif.univ-paris-diderot.fr/~abou/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/ahmedbouajjani/3337b070-be98-4f0a-8133-f5f0b630707f/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in SRC Panel</role>
        <sort_key>22</sort_key>
        <first_name>Timothy</first_name>
        <last_name>Bourke</last_name>
        <affiliation>INRIA</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.tbrk.org</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/timothybourke/747739f4-e5f1-4d96-957d-a9e98c1ba4f7/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>23</sort_key>
        <first_name>Sebastian</first_name>
        <last_name>Burckhardt</last_name>
        <affiliation>Microsoft Research</affiliation>
        <bio>Sebastian Burckhardt was born and raised in Basel, Switzerland, where he studied Mathematics at the local University. During an exchange year at Brandeis University, he discovered his affinity to Computer Science and immigrated to the United States. After a few years of industry experience at IBM, he returned to academia and earned his PhD in Computer Science at the University of Pennsylvania. Since then, he has worked as a researcher at Microsoft Research in Redmond. His general research interest is the study of programming models for of concurrent, parallel, and distributed systems. More specific interests include consistency models, concurrency testing, self-adjusting computation, and the concurrent revisions programming model.</bio>
        <homepage_url>http://research.microsoft.com/en-us/people/sburckha/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/sebastianburckhardt/726ac702-681a-40f8-94d6-c0465e108867/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>24</sort_key>
        <first_name>Michael</first_name>
        <last_name>Carbin</last_name>
        <affiliation>MIT</affiliation>
        <bio>Michael Carbin was a Ph.D. Candidate in Electrical Engineering and Computer Science at MIT. His interests include the design of programming systems that deliver improved performance and resilience by incorporating approximate computing and self-healing. I will be re-joining MIT in January 2016 as an Assistant Professor. In the interim, I will be working at Microsoft Research in Redmond.
His work on program analysis at Stanford University as an undergraduate received an award for Best Computer Science Undergraduate Honors Thesis. As a graduate student, he has received the MIT Lemelson Presidential and Microsoft Research Graduate Fellowships. His recent research on verifying the reliability of programs that execute on unreliable hardware received a best paper award at OOPSLA 2013.</bio>
        <homepage_url>http://people.csail.mit.edu/mcarbin/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/michaelcarbin/fd0efe40-41d3-4eaf-b227-c8fe1a9f6e96/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>25</sort_key>
        <first_name>Aleksandar</first_name>
        <last_name>Chakarov</last_name>
        <affiliation>University of Colorado Boulder</affiliation>
        <bio>My name is Aleksandar Chakarov and I am a recent graduate from the Computer Science PhD Program at the University of Colorado Boulder working with Prof. Sriram Sankaranarayanan. I am a member of the CU Programming Languages and Verification (CUPLV) group and the Verification of Cyber Physical Systems group. My area of focus is the analysis and verification of probabilistic programs. I focus on adopting static analysis and invariant generation techniques to analyze probabilistic systems.</bio>
        <homepage_url>http://www.cs.colorado.edu/~chakarov/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/aleksandarchakarov/ea46e809-01dd-42eb-90d2-baf36ac02b91/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Artifact Evaluation Committee</role>
        <sort_key>26</sort_key>
        <first_name>Van</first_name>
        <last_name>Chan Ngo</last_name>
        <affiliation>Carnegie Mellon University</affiliation>
        <bio>Chan received his Engineer degree from Hanoi University of Technology with excellent ranking, his Master degree in Computer Science (under a French government scholarship, Evariste Galois program) from Joseph Fourier University(University of Grenoble 1), and his Doctorate degree from Inria Rennes, France.</bio>
        <homepage_url>http://channgo2203.github.io</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/vanchanngo/97bc8533-94be-4763-b1e0-35b9aa4ec184/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Program Committee</role>
        <sort_key>27</sort_key>
        <first_name>Bor-Yuh Evan</first_name>
        <last_name>Chang</last_name>
        <affiliation>University of Colorado Boulder</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.colorado.edu/~bec/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/boryuhevanchang/0cbe7e94-aaf8-458b-9670-3892350bc209/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Program Committee</role>
        <sort_key>28</sort_key>
        <first_name>Swarat</first_name>
        <last_name>Chaudhuri</last_name>
        <affiliation>Rice University</affiliation>
        <bio>Swarat Chaudhuri is an assistant professor of computer science at Rice University. He is an expert on methods for automated reasoning about systems, in particular abstract interpretation and model checking, and the application of such methods in computer-aided programming.
Swarat received a bachelor‚Äôs degree in computer science from the Indian Institute of Technology, Kharagpur, in 2001, and a doctoral degree in computer science from the University of Pennsylvania in 2007. From 2008-2011, he was an assistant professor at the Pennsylvania State University, University Park. He is a recipient of the National Science Foundation CAREER award, the ACM SIGPLAN Outstanding Doctoral Dissertation Award, and the Morris and Dorothy Rubinoff Dissertation Award from the University of Pennsylvania.</bio>
        <homepage_url>http://www.cs.rice.edu/~sc40/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/swaratchaudhuri/380a995e-c23e-4571-9f61-4f948b82c975/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Program Committee</role>
        <sort_key>29</sort_key>
        <first_name>Alvin</first_name>
        <last_name>Cheung</last_name>
        <affiliation>University of Washington</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://homes.cs.washington.edu/~akcheung</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/alvincheung/8a51cd19-a395-45c9-8b2c-b121ff910c62/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>30</sort_key>
        <first_name>Adam</first_name>
        <last_name>Chlipala</last_name>
        <affiliation>MIT</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://adam.chlipala.net/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/adamchlipala/def72d03-2975-4c5a-a726-e8a944b77dc9/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>31</sort_key>
        <first_name>Maria</first_name>
        <last_name>Christakis</last_name>
        <affiliation> University of Kent</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://mariachris.github.io/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/mariachristakis/b7bf39cc-368b-44aa-bbcb-c83734e1e8fa/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Artifact Evaluation Committee</role>
        <sort_key>32</sort_key>
        <first_name>Shumo</first_name>
        <last_name>Chu</last_name>
        <affiliation>University of Washington, USA</affiliation>
        <bio>Shumo is a 4th year PhD student at Computer Science &amp;amp; Engineering, University of Washington. He interests in applying formal methods to data management and building data systems in a principled way.</bio>
        <homepage_url>http://shumochu.com/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/shumochu/da171030-a629-449a-951a-08ea17d308f2/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Program Committee</role>
        <sort_key>33</sort_key>
        <first_name>Ravi</first_name>
        <last_name>Chugh</last_name>
        <affiliation>University of Chicago</affiliation>
        <bio>I am an Assistant Professor at the University of Chicago. I enjoy developing and deploying programming language technology ‚Äî type systems, synthesis algorithms, and other program analysis techniques ‚Äî for applications in software engineering and human-computer interaction.</bio>
        <homepage_url>http://people.cs.uchicago.edu/~rchugh</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/ravichugh/ea931b20-b1e1-4e07-b209-ba0b568e315d/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Artifact Evaluation Committee</role>
        <sort_key>34</sort_key>
        <first_name>Alexei</first_name>
        <last_name>Colin</last_name>
        <affiliation>Carnegie Mellon University</affiliation>
        <bio>undefined</bio>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>35</sort_key>
        <first_name>Eva</first_name>
        <last_name>Darulova</last_name>
        <affiliation>MPI-SWS</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://mpi-sws.org/~eva/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/evadarulova/0d98744b-ec94-4a27-b1c0-0d728d54bdb7/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Program Committee</role>
        <sort_key>36</sort_key>
        <first_name>Joseph</first_name>
        <last_name>Devietti</last_name>
        <affiliation>University of Pennsylvania</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://cis.upenn.edu/~devietti/</homepage_url>
        <picture_url>http://pldi17.sigplan.org/getProfileImage/josephdevietti/62850451-b71a-48b2-8b1b-fad646d36052/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in External Review Committee</role>
        <sort_key>37</sort_key>
        <first_name>Alastair</first_name>
        <last_name>Donaldson</last_name>
        <affiliation>Imperial College London</affiliation>
        <bio>Alastair F. Donaldson is a Senior Lecturer in the Department of Computing at Imperial College London, where he leads the Multicore Programming Group. Prior to joining Imperial, he was a Visting Researcher at Microsoft Research Redmond, a Postdoctoral Research Fellow at the University of Oxford, a Research Engineer at Codeplay Software Ltd., and a PhD student at the University of Glasgow.</bio>