<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE event [<!ELEMENT zip_code (#PCDATA)><!ELEMENT url_link_display (#PCDATA)><!ELEMENT url (#PCDATA)><!ELEMENT tracks (track+)><!ELEMENT track (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT timeslot (slot_id?, title, room, date, start_time, end_time, description?, acm_doi?, persons?, tracks?, tags?)><!ELEMENT tags (tag+)><!ELEMENT tag (#PCDATA)><!ELEMENT suffix (#PCDATA)><!ELEMENT subevent_logo_url (#PCDATA)><!ELEMENT subevent_id (#PCDATA)><!ELEMENT subevent (subevent_id?, title, acronym?, subevent_type, description?, room, date, url?, url_link_display?, subevent_logo_url?, acm_doi?, persons?, tracks?, tags?, sponsor?, timeslot*)><!ELEMENT state (#PCDATA)><!ELEMENT start_time (#PCDATA)><!ELEMENT start_date (#PCDATA)><!ELEMENT sponsor (#PCDATA)><!ELEMENT sort_key (#PCDATA)><!ELEMENT slot_id (#PCDATA)><!ELEMENT subevent_type EMPTY><!ATTLIST subevent_type	type (case_study | demonstration | poster | regular | tutorial | workshop) #IMPLIED><!ELEMENT room (#PCDATA)><!ELEMENT role (#PCDATA)><!ELEMENT picture_url (#PCDATA)><!ELEMENT persons (person+)><!ELEMENT person (role, sort_key, first_name, middle_name?, last_name, suffix?, affiliation, acm_profile_id?, email?, bio?, homepage_url?, picture_url?)><!ELEMENT middle_name (#PCDATA)><!ELEMENT location (facility_name, facility_map_url?, address, city, state?, country, zip_code?)><!ELEMENT last_name (#PCDATA)><!ELEMENT homepage_url (#PCDATA)><!ELEMENT first_name (#PCDATA)><!ELEMENT facility_name (#PCDATA)><!ELEMENT facility_map_url (#PCDATA)><!ELEMENT event_type EMPTY><!ATTLIST event_type	type (conference|workshop|symposium) #IMPLIED><!ELEMENT event (event_details, subevent*, timeslot*)><!ELEMENT event_logo_url (#PCDATA)><!ELEMENT event_details (title, acronym, event_type, start_date, end_date, location, description, url?, url_link_display?, event_logo_url?, persons?)><!ELEMENT end_time (#PCDATA)><!ELEMENT end_date (#PCDATA)><!ELEMENT email (#PCDATA)><!ELEMENT description (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT country (#PCDATA)><!ELEMENT city (#PCDATA)><!ELEMENT bio (#PCDATA)><!ELEMENT affiliation (#PCDATA)><!ELEMENT address (#PCDATA)><!ELEMENT acronym (#PCDATA)><!ELEMENT acm_profile_id (#PCDATA)><!ELEMENT acm_doi (#PCDATA)>]>
<event>
  <event_details>
    <title>ECOOP 2016</title>
    <acronym>ECOOP 2016</acronym>
    <event_type type="conference"/>
    <start_date>2016/07/17</start_date>
    <end_date>2016/07/22</end_date>
    <location>
      <facility_name>Congress Center</facility_name>
      <address>Piazza della Pilotta, 4</address>
      <city>Rome</city>
      <country>Italy</country>
    </location>
    <description>The European Conference on Object-Oriented Programming covers all areas of object technology and related software development technologies. Come celebrate the 30th edition in Rome, Italy, on July 17-22, 2016. This year CurryOn, the ECOOP Summer School, the PhD Symposium, and 11 workshops will be all co-located with ECOOP! 
   
 
 
 
 
   
      
    We are happy to announce the AITO Dahl-Nygaard Prizes for 2016. The Junior Prize is awarded to Emina Torlak for her great research potential. The Senior Prize is awarded to James Noble for his outstanding career contributions. The awards will be given during the conference.  Check AITO's DN Prizes page to find out more!  
      
   
 
 

Visit our Facebook and Google+ pages, and stay tuned by following @ECOOPConf:

 

 
 
   
   Sun, July 17 
   Mon, July 18 
   Tue, July 19 
   Wed, July 20 
   Thu, July 21 
   Fri, July 22 
   
   
    PMLDC Distributed Computing  
    Curry On  
    ECOOP  
   
   
    LIVE Live Prog. Systems  
    ICOOOLPS OO Implementation  
    FTfJP FormalTechniques  
   
   
    STOP Scripts to Programs  
    IWACO Aliasing &amp;amp; Ownership  
    GRACE Educational Programming  
  
   
    DoctoralSymposium  
    VORTEX Runtime Verification  
    JSTools JavascriptAnalysis  
    Summer School  
   
   
    PX Programming Experience  
    COP Context Orientation  
   
 
 

 Latest from @ECOOPconf</description>
    <url>http://2016.ecoop.org/home</url>
    <url_link_display>ECOOP 2016</url_link_display>
    <persons>
      <person>
        <role>Publicity chair in Organizing Committee</role>
        <sort_key>1</sort_key>
        <first_name>Emilio</first_name>
        <last_name>Coppa</last_name>
        <affiliation>Sapienza University of Rome, Italy</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://ecoppa.github.io/</homepage_url>
        <picture_url>http://2016.ecoop.org/getProfileImage/emiliocoppa/ac662473-2d0b-4ae4-9b37-324e65a4f883/small.jpg</picture_url>
      </person>
      <person>
        <role>Web &amp; Housing Chair in Organizing Committee</role>
        <sort_key>2</sort_key>
        <first_name>Daniele Cono</first_name>
        <last_name>D'Elia</last_name>
        <affiliation>Sapienza University of Rome, Italy</affiliation>
        <bio>I’m a postdoctoral researcher in the SEASON Lab at Sapienza University of Rome, working on program analysis techniques with applications to online optimization and security.
In my dissertation I tackled two topical problems in adaptive program optimization: fine-grained performance profiling and on-stack replacement. I’m the creator of OSRKit, an OSR library for the LLVM compiler toolchain.</bio>
        <homepage_url>http://www.dis.uniroma1.it/~delia/</homepage_url>
        <picture_url>http://2016.ecoop.org/getProfileImage/danieleconodelia/44ba56db-be0a-445f-bd2c-e9fbbe42381f/small.jpg</picture_url>
      </person>
      <person>
        <role>General Chair in Organizing Committee</role>
        <sort_key>3</sort_key>
        <first_name>Camil</first_name>
        <last_name>Demetrescu</last_name>
        <affiliation>Sapienza University of Rome</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.dis.uniroma1.it/~demetres/</homepage_url>
        <picture_url>http://2016.ecoop.org/getProfileImage/camildemetrescu/d6d70866-6ad9-4516-bfb7-2e1fb26921bd/small.jpg</picture_url>
      </person>
      <person>
        <role>Sponsorship Co-Chair in Organizing Committee</role>
        <sort_key>4</sort_key>
        <first_name>Irene</first_name>
        <last_name>Finocchi</last_name>
        <affiliation>Sapienza University of Rome, Italy</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://wwwusers.di.uniroma1.it/~finocchi/</homepage_url>
        <picture_url>http://2016.ecoop.org/getProfileImage/irenefinocchi/bbbf2db6-7bae-4fce-8215-717a185d141e/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Volunteer Co-Chair in Organizing Committee</role>
        <sort_key>5</sort_key>
        <first_name>Olivier</first_name>
        <last_name>Fluckiger</last_name>
        <affiliation>Northeastern University</affiliation>
        <bio>undefined</bio>
        <picture_url>http://2016.ecoop.org/getProfileImage/olivierfluckiger/413c1991-0ab1-4150-b564-6ec9cf328f5a/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Organizing Committee</role>
        <sort_key>6</sort_key>
        <first_name>Reid</first_name>
        <last_name>Holmes</last_name>
        <affiliation>Confero</affiliation>
        <bio>undefined</bio>
        <picture_url>http://2016.ecoop.org/getProfileImage/reidholmes1/06c9b89d-d2f6-4ca4-ab54-7654e03e44cb/small.jpg</picture_url>
      </person>
      <person>
        <role>Publications Chair in Organizing Committee</role>
        <sort_key>7</sort_key>
        <first_name>Benjamin</first_name>
        <last_name>Lerner</last_name>
        <affiliation>Northeastern University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.ccs.neu.edu/home/blerner</homepage_url>
        <picture_url>http://2016.ecoop.org/getProfileImage/benjaminlerner/91181185-b05b-4e42-bc54-72909b447e59/small.jpg</picture_url>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>8</sort_key>
        <first_name>Paley</first_name>
        <last_name>Li</last_name>
        <affiliation>Northeastern University</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://palez.github.io</homepage_url>
        <picture_url>http://2016.ecoop.org/getProfileImage/paleyli/5f6e3302-652d-4862-b5b6-d621e9b5a653/small.jpg</picture_url>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>9</sort_key>
        <first_name>Francesco</first_name>
        <last_name>Logozzo</last_name>
        <affiliation>Facebook</affiliation>
        <bio>I love static program analysis. I’ve been designing and implementing widely used static analysis tools. I published papers in the most important research conferences and gave talks at main industrial conferences as e.g., Build.</bio>
        <homepage_url>https://it.linkedin.com/in/francesco-logozzo-4106386</homepage_url>
        <picture_url>http://2016.ecoop.org/getProfileImage/francescologozzo/f70bf450-fed8-4488-88cb-579091e43a4d/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Volunteer Co-Chair in Organizing Committee</role>
        <sort_key>10</sort_key>
        <first_name>Petr</first_name>
        <last_name>Maj</last_name>
        <affiliation>ReactorLabs</affiliation>
        <bio>undefined</bio>
        <picture_url>http://2016.ecoop.org/getProfileImage/petrmaj/bb0cb796-8ea6-4a03-bbf7-cd6124195e48/small.jpg</picture_url>
      </person>
      <person>
        <role>Sponsorship Co-Chair in Organizing Committee</role>
        <sort_key>11</sort_key>
        <first_name>Heather</first_name>
        <last_name>Miller</last_name>
        <affiliation>Ecole Polytechnique Federale de Lausanne</affiliation>
        <bio>I am a Research Scientist at EPFL, and the Executive Director of the Scala Center, working on the Scala programming language. In October 2015, I earned my PhD under the supervision of Professor Martin Odersky the Programming Methods Laboratory (LAMP for short) at EPFL. Before moving to Switzerland, I was born in and lived all over the US.
I’m interested in programming language and compiler support for distributed programming. In particular, I’m interested in using type systems to facilitate the design of new, functional distributed systems.</bio>
        <homepage_url>http://heather.miller.am/</homepage_url>
        <picture_url>http://2016.ecoop.org/getProfileImage/heathermiller/bcbc4db2-52f8-4135-b4ab-5bf33879d8dd/small.jpg</picture_url>
      </person>
      <person>
        <role>Treasurer &amp; Conference Manager in Organizing Committee</role>
        <sort_key>12</sort_key>
        <first_name>Annabel</first_name>
        <last_name>Satin</last_name>
        <affiliation>undefined</affiliation>
        <bio>undefined</bio>
        <picture_url>http://2016.ecoop.org/getProfileImage/annabelsatin/de3bb293-96c3-4a34-98b2-e7c46f9e53e8/small.jpg</picture_url>
      </person>
      <person>
        <role>Comfy Chair in Organizing Committee</role>
        <sort_key>13</sort_key>
        <first_name>Jan</first_name>
        <last_name>Vitek</last_name>
        <affiliation>Northeastern University</affiliation>
        <bio>Jan Vitek is a Professor of Computer Science at Northeastern University. Dr. Vitek was born in Czechoslovakia and educated in Switzerland. Over the years, he worked on topics related to programming languages, their design, use, and implementation. With Noble and Potter, he proposed the notion of flexible alias control which became know as Ownership Types. He led the Ovm project which produced the first real-time Java virtual machine to be flight tested on a ScanEagle drone (he claims no one was harmed). Outcomes of this project include the Schism real-time garbage collector and the FijiVM – a production VM for embedded systems. More recently, he worked on dynamic languages, trying to make sense of JavaScript and to design a new language called, Thorn. Nowadays, he spends his time with statisticians and data scientists. Jan believes that his 2012 election as Chair of SIGPLAN was an accident; since has been busy trying to rock the boat to ensure this does not happen again. In his spare time, Jan enjoys organizing conferences and sitting on PCs (over 25 in the last decade). He founded the MOS (mobile objects), IWACO (alias control), STOP (gradual typing), and TRANSACT (transactional memory) workshop series. He was the first program chair of VEE and chaired ESOP, ECOOP, Coordination and TOOLS. He was the general chair of PLDI (in Beijing!), ISMM and LCTES. He may still be sitting on the steering committees of ECOOP, JTRES, ICFP, OOPLSA, POPL, PLDI, LCTES, ESOP.</bio>
        <homepage_url>http://janvitek.org</homepage_url>
        <picture_url>http://2016.ecoop.org/getProfileImage/janvitek/53f115e3-8db9-4b80-b49a-f5eb2a0c8696/small.jpg</picture_url>
      </person>
    </persons>
  </event_details>
  <subevent>
    <subevent_id>0814216e-65be-4750-949f-c6553696db06</subevent_id>
    <title>VORTEX: Session 2</title>
    <subevent_type type="regular"/>
    <room>Saba</room>
    <date>2016/07/18</date>
    <url>http://2016.ecoop.org/track/VORTEX-2016</url>
    <url_link_display>VORTEX</url_link_display>
    <tracks>
      <track>VORTEX</track>
    </tracks>
    <timeslot>
      <slot_id>130c1670-ef53-4ed1-8d0f-739e6b37c306</slot_id>
      <title>The Early Bird Catches the Worm: first Verify, then Monitor!</title>
      <room>Saba</room>
      <date>2016/07/18</date>
      <start_time>14:50</start_time>
      <end_time>15:19</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Angelo</first_name>
          <last_name>Ferrando</last_name>
          <affiliation>undefined</affiliation>
          <bio>undefined</bio>
        </person>
      </persons>
      <tracks>
        <track>VORTEX</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>40b9ffb7-e262-4b19-875a-e1a4acff8f4c</slot_id>
      <title>Closing Remarks</title>
      <room>Saba</room>
      <date>2016/07/18</date>
      <start_time>15:19</start_time>
      <end_time>15:20</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Davide</first_name>
          <last_name>Ancona</last_name>
          <affiliation>University of Genova</affiliation>
          <bio>Davide Ancona (PhD in Computer Science, University of Pisa, 1998) is Associate Professor at the University of Genova. His main research interests include type systems, object-oriented programming, coinduction methods for programming languages, modules and components, software reuse and maintenance, multi-agent systems, and behavioral types. He is author of more than 70 publications. He is the secretary of the executive board of AITO, Association Internationale pour les Technologies Objets (since Jan 2013, previously Vice-President since Jan 2012), and member of the editorial board of the Central European Journal of Computer Science and of the ACM/SIGAPP Applied Computing Review (ACR). He has been guest editor of special issues of Science of Computer Programming and Journal of Object Technology. In 2009 he received, together with G. Lagorio, the best paper prize at ECOOP. He has participated to several national and European projects and has been PC member of several workshops and conferences: WOOD’04, Bytecode 2008, ESOP 2008, DLS 2009, 2010 and 2013, FOOL 2010, RP 2011 and 2012, ECOOP 2013 and 2014, POPL 2015 (External Reviewing Committee). He has been involved in the organization of several scientific events: organizing chair of ECOOP 2009, program co-chair of FTfJP06 and of OOPS special track at SAC from 2004 through 2015, co-chair of CILC 2015.</bio>
          <homepage_url>http://www.disi.unige.it/person/AnconaD/</homepage_url>
          <picture_url>http://2016.ecoop.org/getProfileImage/davideancona/b3d19c77-a788-469b-ab47-7c6f3134f87d/small.jpg</picture_url>
        </person>
        <person>
          <role>Author</role>
          <sort_key>2</sort_key>
          <first_name>Frank S.</first_name>
          <last_name>de Boer</last_name>
          <affiliation>Centrum Wiskunde &amp; Informatica, Leiden University</affiliation>
          <bio>undefined</bio>
          <homepage_url>http://homepages.cwi.nl/~frb/</homepage_url>
          <picture_url>http://2016.ecoop.org/getProfileImage/franksdeboer/ffdb7b27-277c-4985-a5c6-4cf6961ab4c7/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>VORTEX</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>65d443f3-b3c5-44b8-a305-2b2204e423db</slot_id>
      <title>Extracting Runtime Monitors from Tests: An Overview and a way forward</title>
      <room>Saba</room>
      <date>2016/07/18</date>
      <start_time>13:50</start_time>
      <end_time>14:20</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Abigail</first_name>
          <last_name>Cauchi</last_name>
          <affiliation>undefined</affiliation>
          <bio>undefined</bio>
        </person>
        <person>
          <role>Author</role>
          <sort_key>2</sort_key>
          <first_name>Luke</first_name>
          <last_name>Chircop</last_name>
          <affiliation>undefined</affiliation>
          <bio>undefined</bio>
        </person>
        <person>
          <role>Author</role>
          <sort_key>3</sort_key>
          <first_name>Christian</first_name>
          <last_name>Colombo</last_name>
          <affiliation>undefined</affiliation>
          <bio>undefined</bio>
        </person>
        <person>
          <role>Author</role>
          <sort_key>4</sort_key>
          <first_name>Adrian</first_name>
          <last_name>Francalanza</last_name>
          <affiliation>undefined</affiliation>
          <bio>undefined</bio>
        </person>
        <person>
          <role>Author</role>
          <sort_key>5</sort_key>
          <first_name>Mark</first_name>
          <last_name>Micallef</last_name>
          <affiliation>undefined</affiliation>
          <bio>undefined</bio>
        </person>
        <person>
          <role>Author</role>
          <sort_key>6</sort_key>
          <first_name>Gordon</first_name>
          <last_name>Pace</last_name>
          <affiliation>University of Malta</affiliation>
          <bio>undefined</bio>
          <homepage_url>http://www.cs.um.edu.mt/gordon.pace</homepage_url>
          <picture_url>http://2016.ecoop.org/getProfileImage/gordonpace/4b52eb89-123e-43c8-9bcd-9221fb293173/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>VORTEX</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>e21cac41-a57f-4b53-9c13-d2c4f8439efb</slot_id>
      <title>Runtime checks as nominal types</title>
      <room>Saba</room>
      <date>2016/07/18</date>
      <start_time>14:20</start_time>
      <end_time>14:50</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Paola</first_name>
          <last_name>Giannini</last_name>
          <affiliation>undefined</affiliation>
          <bio>undefined</bio>
        </person>
        <person>
          <role>Author</role>
          <sort_key>2</sort_key>
          <first_name>Elena</first_name>
          <last_name>Zucca</last_name>
          <affiliation>University of Genova</affiliation>
          <bio>undefined</bio>
          <homepage_url>http://www.disi.unige.it/person/ZuccaE/</homepage_url>
        </person>
        <person>
          <role>Author</role>
          <sort_key>3</sort_key>
          <first_name>Marco</first_name>
          <last_name>Servetto</last_name>
          <affiliation>Victoria University of Wellington</affiliation>
          <bio>undefined</bio>
        </person>
      </persons>
      <tracks>
        <track>VORTEX</track>
      </tracks>
    </timeslot>
  </subevent>
  <subevent>
    <subevent_id>cd06e7e6-8ab4-4898-a9e3-dc25635014be</subevent_id>
    <title>VORTEX: Session 1</title>
    <subevent_type type="regular"/>
    <room>Saba</room>
    <date>2016/07/18</date>
    <url>http://2016.ecoop.org/track/VORTEX-2016</url>
    <url_link_display>VORTEX</url_link_display>
    <tracks>
      <track>VORTEX</track>
    </tracks>
    <timeslot>
      <slot_id>59ffafa7-1477-463a-b0ec-7ac15d97916a</slot_id>
      <title> Monitoring JavaScript Programs with Jalangi</title>
      <room>Saba</room>
      <date>2016/07/18</date>
      <start_time>11:40</start_time>
      <end_time>12:10</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Koushik</first_name>
          <last_name>Sen</last_name>
          <affiliation>University of California, Berkeley</affiliation>
          <bio>Koushik Sen is an associate professor in the Department of Electrical Engineering and Computer Sciences at the University of California, Berkeley. His research interest lies in Software Engineering, Programming Languages, and Formal methods. He is interested in developing software tools and methodologies that improve programmer productivity and software quality. He is best known for his work on “DART: Directed Automated Random Testing” and concolic testing. He has received a NSF CAREER Award in 2008, a Haifa Verification Conference (HVC) Award in 2009, a IFIP TC2 Manfred Paul Award for Excellence in Software: Theory and Practice in 2010, a Sloan Foundation Fellowship in 2011, a Professor R. Narasimhan Lecture Award in 2014, and an Okawa Foundation Research Grant in 2015. He has won several ACM SIGSOFT Distinguished Paper Awards. He received the C.L. and Jane W-S. Liu Award in 2004, the C. W. Gear Outstanding Graduate Award in 2005, and the David J. Kuck Outstanding Ph.D. Thesis Award in 2007, and a Distinguished Alumni Educator Award in 2014 from the UIUC Department of Computer Science. He holds a B.Tech from Indian Institute of Technology, Kanpur, and M.S. and Ph.D. in CS from University of Illinois at Urbana-Champaign.</bio>
          <homepage_url>http://srl.cs.berkeley.edu/~ksen/</homepage_url>
          <picture_url>http://2016.ecoop.org/getProfileImage/koushiksen/acb915fb-8e52-49dc-973e-eb9172c3d462/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>VORTEX</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>661fc94b-62fe-416f-a71e-4a6eb5c5097a</slot_id>
      <title>StaRVOOrS: A framework for static and runtime verification of data and control properties.</title>
      <room>Saba</room>
      <date>2016/07/18</date>
      <start_time>10:10</start_time>
      <end_time>10:40</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Gerardo</first_name>
          <last_name>Schneider</last_name>
          <affiliation>University of Gothenburg</affiliation>
          <bio>undefined</bio>
          <homepage_url>http://www.cse.chalmers.se/~gersch/</homepage_url>
          <picture_url>http://2016.ecoop.org/getProfileImage/gerardoschneider/88dbc706-4a1c-4417-b1ed-6ac04ce4bbe5/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>VORTEX</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>a1c82b05-66be-4814-902e-fe800cc8ea80</slot_id>
      <title>Runtime Verification with Data</title>
      <room>Saba</room>
      <date>2016/07/18</date>
      <start_time>10:40</start_time>
      <end_time>11:10</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Martin</first_name>
          <last_name>Leucker</last_name>
          <affiliation>University of Lübeck</affiliation>
          <bio>undefined</bio>
          <homepage_url>https://www.isp.uni-luebeck.de/leucker</homepage_url>
          <picture_url>http://2016.ecoop.org/getProfileImage/martinleucker/a3679181-6daf-4256-b932-1d8235d4c0ba/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>VORTEX</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>b07e3bea-7693-4684-9c17-1c8b011f551d</slot_id>
      <title>Runtime Verification of Safe Advisories in the Next-Generation Airborne Collision Avoidance System</title>
      <room>Saba</room>
      <date>2016/07/18</date>
      <start_time>11:10</start_time>
      <end_time>11:40</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Jean-Baptiste</first_name>
          <last_name>Jeannin</last_name>
          <affiliation>Carnegie Mellon University	</affiliation>
          <bio>I am a Researcher at Samsung Research America in Mountain View, California. Before that I was a Post Doctoral Fellow working with Andr&amp;eacute; Platzer in the Logical Systems Lab at Carnegie Mellon University. I received my Ph.D. in Computer Science from Cornell University in 2013, where I was advised by Dexter Kozen. I also received a Master of Engineering in Computer Science from Cornell University in 2008, and a Dipl&amp;ocirc;me d’Ing&amp;eacute;nieur from &amp;Eacute;cole polytechnique in 2007.</bio>
          <homepage_url>http://www.cs.cmu.edu/~jeannin/</homepage_url>
          <picture_url>http://2016.ecoop.org/getProfileImage/jeanbaptistejeannin/a95f84e4-d955-43d9-9927-37572a9da843/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>VORTEX</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>ffc8d752-4f4b-4056-9db5-827411465321</slot_id>
      <title>Opening Remarks</title>
      <room>Saba</room>
      <date>2016/07/18</date>
      <start_time>10:05</start_time>
      <end_time>10:10</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Davide</first_name>
          <last_name>Ancona</last_name>
          <affiliation>University of Genova</affiliation>
          <bio>Davide Ancona (PhD in Computer Science, University of Pisa, 1998) is Associate Professor at the University of Genova. His main research interests include type systems, object-oriented programming, coinduction methods for programming languages, modules and components, software reuse and maintenance, multi-agent systems, and behavioral types. He is author of more than 70 publications. He is the secretary of the executive board of AITO, Association Internationale pour les Technologies Objets (since Jan 2013, previously Vice-President since Jan 2012), and member of the editorial board of the Central European Journal of Computer Science and of the ACM/SIGAPP Applied Computing Review (ACR). He has been guest editor of special issues of Science of Computer Programming and Journal of Object Technology. In 2009 he received, together with G. Lagorio, the best paper prize at ECOOP. He has participated to several national and European projects and has been PC member of several workshops and conferences: WOOD’04, Bytecode 2008, ESOP 2008, DLS 2009, 2010 and 2013, FOOL 2010, RP 2011 and 2012, ECOOP 2013 and 2014, POPL 2015 (External Reviewing Committee). He has been involved in the organization of several scientific events: organizing chair of ECOOP 2009, program co-chair of FTfJP06 and of OOPS special track at SAC from 2004 through 2015, co-chair of CILC 2015.</bio>
          <homepage_url>http://www.disi.unige.it/person/AnconaD/</homepage_url>
          <picture_url>http://2016.ecoop.org/getProfileImage/davideancona/b3d19c77-a788-469b-ab47-7c6f3134f87d/small.jpg</picture_url>
        </person>
        <person>
          <role>Author</role>
          <sort_key>2</sort_key>
          <first_name>Frank S.</first_name>
          <last_name>de Boer</last_name>
          <affiliation>Centrum Wiskunde &amp; Informatica, Leiden University</affiliation>
          <bio>undefined</bio>
          <homepage_url>http://homepages.cwi.nl/~frb/</homepage_url>
          <picture_url>http://2016.ecoop.org/getProfileImage/franksdeboer/ffdb7b27-277c-4985-a5c6-4cf6961ab4c7/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>VORTEX</track>
      </tracks>
    </timeslot>
  </subevent>
  <subevent>
    <subevent_id>f7dc715a-0313-48ab-a1cd-3ec93f17f5f1</subevent_id>
    <title>IWACO: Session 2</title>
    <subevent_type type="regular"/>
    <room>Quasimodo</room>
    <date>2016/07/18</date>
    <url>http://2016.ecoop.org/track/IWACO-2016</url>
    <url_link_display>IWACO</url_link_display>
    <tracks>
      <track>IWACO</track>
    </tracks>
    <timeslot>
      <slot_id>07a7253e-261f-4007-bed0-c622ca29009c</slot_id>
      <title>Are Ownership Types Reaching the World Yet?</title>
      <room>Quasimodo</room>
      <date>2016/07/18</date>
      <start_time>16:00</start_time>
      <end_time>16:30</end_time>